name: Run tests on PR

on:
  pull_request:
    branches: [ main ]

jobs:
  games:
    name: Test Games
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.17.x'

      - name: Install dependencies
        run: |
          go get .

      - name: Test
        run: go test -v pkg.satheesh.dev/boom/games
